### ISSUE TITLE
[Bug] r.mask behavior for zero is incorrect or at least confusing

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass#1842]
**Describe the bug**
r.mask manual says:

> Grid cells in the MASK map containing <tt>0</tt> or <tt>NULL</tt> will replace data with NULL, while cells containing other values will allow data to pass through unaltered.

which is technically correct, but that doesn't say anything about how r.mask works with zeros in the source raster.
So for example if you have binary raster (0 and 1) and run `r.mask raster=binary` it will produce unintuitively mask covering everything and not just the 1s. To produce the expected mask you would have to use `r.mask raster=binary maskcats=1`.

**To Reproduce**
```
g.region raster=elevation@PERMANENT 
r.mapcalc expression="binary = rand(0,2)"
r.univar map=binary
# total null cells: 0
r.mask raster=binary
r.univar map=binary
# total null cells: 0    <--- problem
r.mask raster=binary maskcats=1 --o
r.univar map=binary
# total null cells: 1012515
```
**Expected behavior**
I would expect zeros in the source raster to be by default interpreted as NULLs and lead to masking out, which would be consistent with how the MASK itself works.

**Comment by ecodiv** [comment]
I would argue against interpreting 0 (zero) in a source raster as NULL. It is a valid value, just like any other, and any special treatment would be confusing i.m.h.o. In addition, what about raster layers with values ranging from some negative to some positive number, and I want to use all values as part of the MASK?

**Comment by petrasovaa** [comment]
> I would argue against interpreting 0 (zero) in a source raster as NULL. It is a valid value, just like any other, and any special treatment would be confusing i.m.h.o. In addition, what about raster layers with values ranging from some negative to some positive number, and I want to use all values as part of the MASK?

I understand your concern, but the issue is currently the situation is inconsistent - zeros in the raster MASK itself are being interpreted as masked out. So then we would have to change how the library deals with that. I don't have a strong opinion either way, although my first thought was to use zeros as NULLs.

**Comment by ecodiv** [comment]
I never really gave the inner works of a MASK much thought, assuming it was just a (raster reclassified to a) map with 1 and NULL. Unless there is a good reason I am not aware of that a MASK could also have zeros, for me the following behaviour would be most intuitive:

_Grid cells in the MASK map containing NULL will replace data in the input raster with NULL, while cells containing other values will allow data to pass through unaltered._

**Comment by metzm** [comment]
That seems to be a feature in `r.mask`: by default any non-NULL value, also zero, is converted to 1, unless maskcats is given. If you want to use a binary raster with [0, 1] as mask, you could alternatively copy that raster to MASK (`g.copy rast=binayry,MASK`).

The manual saying
```
Grid cells in the MASK map containing 0 or NULL will replace data with NULL, while cells containing other values will allow data to pass through unaltered.
```
is correct. This is about an existing MASK map interpreted by the raster lib, and not how `r.mask` creates a MASK map.

**Comment by ecodiv** [comment]
The way r.mask works seems logical to me.  However, I agree with @petrasovaa that the fact that the raster lib can work with MASK layers that contain zeros (i.e., raster layers that are different from the ones r.mask creates) can be somewhat confusing.  

The confusion is exacerbated, in my view, because the explanation of how a MASK map is interpreted by the raster lib is mentioned in the manual page of r.mask. Yet, r.mask does not create a map with zeros and NULL, only with 1 and NULL.

Perhaps remove the sentence "Grid cells in the MASK map containing 0 or NULL will replace data with NULL, while cells containing other values will allow data to pass through unaltered" from the DESCRIPTION section. As that sentence is only relevant if you create a MASK file in another way than with r.mask (if I understand correctly), it makes more sense to move it to the end of the NOTES section, where other ways to create a MASK are mentioned. Together with the example from @metzm above, this would clarify a lot I think.

I can try to reword the text in the manual page if you like, but of course, only if my interpretation above is correct :-)

**Comment by petrasovaa** [comment]
> I can try to reword the text in the manual page if you like, but of course, only if my interpretation above is correct :-)

Greatly appreciated, I think your suggestion makes sense. I would perhaps mention explicitly how 0 behaves with r.mask.
