### ISSUE TITLE
[Bug] CI error: flake8 Expected - Waiting for status to be reported 

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1935]
**Describe the bug**
Maybe well known but I see numerous PRs failing with

`flake8 Expected — Waiting for status to be reported`

This happens esp. with pure C language PRs where a flake8 test doesn't make too much sense.

C related changes:

- #1507
- #1617
- #1694
- #1708
- #1724
- ...

But also Python changes
- #1559
- #1578
- #1609
- #1643
- #1663
- ...

It would be nice to see the flake8 test treated in a better way.

**Comment by agiudiceandrea** [comment]
@neteler @ninsbl what about https://github.com/OSGeo/grass/pull/1694?

**Comment by wenzeslaus** [comment]
> This happens...with pure C language PRs...It would be nice to see the flake8 test treated in a better way.

One reason the test is required is a limitation of GitHub: You cannot avoid accidental pushes from local repos to the main branch in any other way than requiring a one of the test jobs to pass, but what the job actually does is not important in the context of protecting the branch. With the branch protection rule requiring a passed check, a PR is required for modifying the branch because that's the only way how to get a job running on relevant code before the actual push.

The check depends on the particular name of the job, so for old PRs, there is simply no job of that name (and that's why close/open or code update is needed to trigger new jobs).

**Comment by neteler** [comment]
Issue seems to be gone, closing.
