### ISSUE TITLE
[Bug] Typo in i.vi.html + C code formatting

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1998]
Typo introduced in 6fb6afd:

https://github.com/OSGeo/grass/blob/6fb6afdd94fd803d9ad03ab2e79eaacd17859cee/imagery/i.vi/i.vi.html#L87

-> "fl" ligature has been eaten and needs to be written with two chars.

Also add the full citation of Karnieli, 1997.

Please also fix the C formatting in imagery/i.vi/ci.c using `utils/grass_indent.sh`

@YannChemin - a wish: kindly offer the time to others to review a PR.

**Comment by wenzeslaus** [comment]
@YannChemin Since we are talking about best practices - not that this would be written anywhere, you just learn by doing - please also use your fork on GitHub rather than the OSGeo repo to create branches, i.e., use the same approach as the people from outside of the development team have to use, see [CONTRIBUTING.md](https://github.com/OSGeo/grass/blob/main/CONTRIBUTING.md). As a part of the team, you have the power to create branches in the OSGeo/grass repo, but that's meant for some more long term branches, mostly so you can create new release branches if needed. (Contributions towards documenting this somewhere are of course welcome.)

**Comment by YannChemin** [comment]
thanks,
at this point i just dont understand anything but i guess things have
changed from cvs and svn with git then github.

i will read and maybe understand it one day.
