### ISSUE TITLE
[Bug] wxGUI: SpinCtrl(): arguments did not match any overloaded call: with Python 3.10

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#2049]
**Describe the bug**

At time the graphical "Vector network analysis tool" cannot be started:

```
Traceback (most recent call last):
  File "/home/mneteler/software/grass80/dist.x86_64-pc-
linux-gnu/gui/wxpython/mapdisp/frame.py", line 1599, in
OnVNet

self.dialogs["vnet"] = VNETDialog(parent=self,
giface=self._giface)
  File "/home/mneteler/software/grass80/dist.x86_64-pc-
linux-gnu/gui/wxpython/vnet/dialogs.py", line 154, in
__init__

self._createPointsPage()
  File "/home/mneteler/software/grass80/dist.x86_64-pc-
linux-gnu/gui/wxpython/vnet/dialogs.py", line 283, in
_createPointsPage

self.anSettings["max_dist"] = SpinCtrl(
  File "/home/mneteler/software/grass80/dist.x86_64-pc-
linux-gnu/gui/wxpython/gui_core/wrap.py", line 161, in
__init__

wx.SpinCtrl.__init__(self, *args, **kwargs)
TypeError
:
SpinCtrl(): arguments did not match any overloaded call:
  overload 1: 'parent' is not a valid keyword argument
  overload 2: argument 'max' has unexpected type 'float'
```

**To Reproduce**

1. Display manager > Analyse map
2. Select "Vector network analysis tool" from menu
3. See error.

Same with "Add map elements" > " Add scale bar" and maybe others.

**System description (please complete the following information):**

- Operating System: Fedora 35
- This problem affects both G7.8 and G8.0

```
GRASS version: 7.8.7dev                                                         
Code revision: f9f30f33f                                                        
Build date: 2021-12-14                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.3.2                                                                     
PROJ: 8.2.0                                                                     
GEOS: 3.9.2                                                                     
SQLite: 3.36.0                                                                  
Python: 3.10.1                                                                  
wxPython: 4.0.7                                                                 
Platform: Linux-5.15.6-200.fc35.x86_64-x86_64-with-glibc2.34
```

Note: this is wxPython: 4.0.7-23 (i.e., with multiple recent patches to make the wxGUI start).

**Comment by neteler** [comment]
Thanks to PR #2050 this works again in G8.0.

A backport of #2050 will likely fix it in G7.8.7 as well, keeping issue open.

**Comment by neteler** [comment]
Problem solved in ecd13587d7ccde56b9f443ee884870076983c471

**Comment by ewCrg** [comment]
Neteler, this issue also breaks GRASS 7.8.6 on a fresh installation of fedora 35. My experience has been that any GUI having anything to do with vector files fails (display as well as other modules) to come up, with the traceback message that you've created this bug report under.

Since based on my browsing around github the fix appears to involve numerous python scripts, and since I'm not well versed with github (yet), I've managed to "fix" the issue by replacing the entire /usr/lib64/grass78/gui/wxpython directory that was installed using dnf by "borrowing" and replacing same copied from from the daily generic binary snapshot of Grass 7.8.7 from grass.osgeo.org. Now all appears to work correctly, except for the Layer Manager, where the top field remains blank until I click on something farther down the list, which brings the the layer (file name) text up in the top field, but causes the field being clicked on to go blank (instead of being highlighted).

While I believe that the Layer Manager issue is likely a separate one (I'll search to see if that a bug report on that and if there is none, start a new bug report), might I suggest that perhaps doing a backport of the fixes to this issue to 7.8.6-2.fc35 as well could help others, since f36 (based on file size comparisons, it appears that these fixes may not have been applied to GRASS 7.8.6-3.fc36 either?) has not yet been formally released? Or is this something that I should report to bugzilla.redhat.com?

**Comment by neteler** [comment]
> Neteler, this issue also breaks GRASS 7.8.6 on a fresh installation of fedora 35.

The fixes will be published in the upcoming GRASS 7.8.7 version.

It would be too much for me (as the Fedora packager) to patch 7.8.6 in Fedora. If there is any volunteer, please open a pull request at https://src.fedoraproject.org/rpms/grass by picking them from [this list of changes](https://github.com/OSGeo/grass/compare/7.8.6...releasebranch_7_8).

Note that the GRASS 7.8.7 release is very close, see:
https://lists.osgeo.org/pipermail/grass-dev/2022-January/095524.html

**Comment by ewCrg** [comment]
Hi Markus, with GRASS 7.8.7 being so close and available as an update, then I see no sense in resources going into patching/re-releasing 7.8.6. I'll also wait to see if 7.8.7 fixes the Layer Manager issue before following up on that. Thanks

**Comment by neteler** [comment]
> Hi Markus, with GRASS 7.8.7 being so close and available as an update, then I see no sense in resources going into patching/re-releasing 7.8.6. I'll also wait to see if 7.8.7 fixes the Layer Manager issue before following up on that. Thanks

Hi @ewCrg, you can now try GRASS GIS 7.8.7RC1, released yesterday - available as source code. Also here for Fedora: https://copr.fedorainfracloud.org/coprs/neteler/grass78/ (the official package will follow once "final" has been released).
