### ISSUE TITLE
[Feat] CI: add support for [skip ci]

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#2174]
**Is your feature request related to a problem? Please describe.**

At time the full CI is run even when only `doc/howto_release.md` is edited which does not require CI checks at all.
This is a waste of runner resources.

**Describe the solution you'd like**

Like in the GDAL repo, add support for `[skip ci]` or  `[ci skip]`.

Note: Once implemented, the contributor needs to carefully decide if their PR submission may skip CI or not (it will rather be an exception to skip it).

**Comment by wenzeslaus** [comment]
Why not use `paths-ignore` like in the [CodeQL workflow](https://github.com/OSGeo/grass/blob/main/.github/workflows/codeql-analysis.yml)?

Instead of having a system when _the contributor needs to carefully decide_, `paths-ignore` or `paths` clearly decide on which PR or commit they should run.

**Comment by neteler** [comment]
> Why not use `paths-ignore` like in the [CodeQL workflow](https://github.com/OSGeo/grass/blob/main/.github/workflows/codeql-analysis.yml)?

Ah, I wasn't aware of that possibility.

> Instead of having a system when _the contributor needs to carefully decide_, `paths-ignore` or `paths` clearly decide on which PR or commit they should run.

Sounds good. I'll make a new attempt. Best would be to save these ignore-paths to a single file rather than replicating them in all workflows. Would that be possible?

**Comment by neteler** [comment]
See new PR #2176

**Comment by nilason** [comment]
I think we should start to use this as soon as possible. https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

**Comment by wenzeslaus** [comment]
I don't know how well the skip would work, the concurrency config for workflows seemed more hopeful, maybe combined with running specific checks for specific files.

**Comment by neteler** [comment]
This looks interesting:

https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters-to-target-specific-paths-for-pull-request-or-push-events

**Comment by echoix** [comment]
Well, technically, skipping ci completely works natively since February 2021, I tested it in my fork just now, and none of the workflow was run, just like that blog post announcing it describes:

https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/


Knowing this, what exactly is the purpose of this issue? There are already some path filtering done in our workflows, like the docker one, and skipping CI works natively.

What is missing?

**Comment by neteler** [comment]
Nice, seems nobody ever tried it out so far.

**Comment by wenzeslaus** [comment]
I think this is resolved and being resolved by faster workflows, so I'm closing this.

For skip itself, I would advice caution with `[skip ci]` outside of a PR branch because, well, it is `[disable useful checks which help us prevent issues]`. For main and possibly release branches in the future, see [Skipping workflow runs](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs) in the doc:

> You won't be able to merge the pull request if your repository is configured to require specific checks to pass first. To allow the pull request to be merged you can push a new commit to the pull request without the skip instruction in the commit message.

Importantly, the GitHub feature is mainly useful for skipping checks when pushing a lot of small or anyway unchecked changes to a PR branch, i.e., in a "sandbox" of a PR. (This is different from the idea in the OP where contributors needs to carefully decide about the nature of the changes even for merge to main.)
