### ISSUE TITLE
[Bug] g.region -n  Flag broken

### ISSUE THREAD

**Issue by joneir** [OSGeo/grass#2257]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior - my session:

 ________________________________________________________________________________ 
| ~ @ uppsetnings-iMac (jeir) 
| => /Applications/GRASS-8.0.app/Contents/MacOS/Grass.sh
Rebuilding Addon HTML manual pages index...
cp: directory /Users/jeir/Library/GRASS/8.0/Modules/docs/html does not exist
cp: directory /Users/jeir/Library/GRASS/8.0/Modules/docs/html does not exist
cp: directory /Users/jeir/Library/GRASS/8.0/Modules/docs/html does not exist
/Applications/GRASS-8.0.app/Contents/MacOS/build_html_user_index.sh: line 104: cd: /Users/jeir/Library/GRASS/8.0/Modules/docs/html: No such file or directory
Rebuilding Addon menu...
/Applications/GRASS-8.0.app/Contents/MacOS/build_gui_user_menu.sh: line 58: cd: /Users/jeir/Library/GRASS/8.0/Modules/bin: No such file or directory
Default locale settings are missing. GRASS running with C locale.
Starting GRASS GIS...
Cleaning up temporary files...

          __________  ___   __________    _______________
         / ____/ __ \/   | / ___/ ___/   / ____/  _/ ___/
        / / __/ /_/ / /| | \__ \\_  \   / / __ / / \__ \
       / /_/ / _, _/ ___ |___/ /__/ /  / /_/ // / ___/ /
       \____/_/ |_/_/  |_/____/____/   \____/___//____/

Welcome to GRASS GIS 8.0.0
GRASS GIS homepage:                      https://grass.osgeo.org
This version running through:            Bash Shell (/bin/bash)
Help is available with the command:      g.manual -i
See the licence terms with:              g.version -c
See citation options with:               g.version -x
If required, restart the GUI with:       g.gui wxpython
When ready to quit enter:                exit

Launching <wxpython> GUI in the background, please wait...

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.

GRASS nc_spm_08_grass7/user1:~ > g.region -p
projection: 99 (Lambert Conformal Conic)
zone:       0
datum:      nad83
ellipsoid:  a=6378137 es=0.006694380022900787
north:      220750
south:      220000
west:       638300
east:       639000
nsres:      1
ewres:      1
rows:       750
cols:       700
cells:      525000

GRASS nc_spm_08_grass7/user1:~ > g.region -n
Invalid latitude or longitude
convergence angle: 0.000000
GRASS nc_spm_08_grass7/user1:~ > 

**Expected behavior**

expected return of convergence angle

**Screenshots**

**System description (please complete the following information):**

- Operating System: [macosx 12.2.1]
- GRASS GIS version [8.0]

**Additional context**

Also broken in version 7.8

**Comment by HuidaeCho** [comment]
Hmm.... I'm getting this error from the NC sample dataset:
```
> g.region -n
Invalid type for P object
convergence angle: 0.000000
```
That error comes from:
https://github.com/OSGeo/grass/blob/8b4ccfb47f34da4178bb24df5649fdf0f3ff4857/general/g.region/printwindow.c#L518

So I checked the type of P:
```c
printf("iproj.pj type: %d %d\n", proj_get_type(iproj.pj), PJ_TYPE_BOUND_CRS);
```
Well, EPSG:3358 should be a projected CRS, not a bound CRS. PROJ cannot (doesn't?) calculate factors for a bound CRS:
https://github.com/OSGeo/PROJ/blob/dc02907ada045544179dcad0e11e0717d6dcf621/src/4D_api.cpp#L2499-L2507

Adding
```c
for(i = 0; i < nopt; i++)printf("%s\n", opt_in[i]);
```
above
https://github.com/OSGeo/grass/blob/8b4ccfb47f34da4178bb24df5649fdf0f3ff4857/lib/proj/get_proj.c#L252
prints
```
proj=lcc
lat_1=36.16666666666666
lat_2=34.33333333333334
lat_0=33.75
lon_0=-79
x_0=609601.22
y_0=0
no_defs
a=6378137
rf=298.257222101
towgs84=0.000,0.000,0.000
type=crs
```
and feeding this output to projinfo gives a bound CRS.
```
> projinfo "proj=lcc lat_1=36.16666666666666 lat_2=34.33333333333334 lat_0=33.75 lon_0=-79 x_0=609601.22 y_0=0 no_defs a=6378137 rf=298.257222101 towgs84=0.000,0.000,0.000 type=crs" -o PROJJSON | grep BoundCRS
  "type": "BoundCRS",
```
g.proj is OK.
```
> projinfo "`g.proj -j`" -o PROJJSON | grep ProjectedCRS
  "type": "ProjectedCRS",
```
`g.proj -j` outputs:
```
+proj=lcc
+lat_0=33.75
+lon_0=-79
+lat_1=36.1666666666667
+lat_2=34.3333333333333
+x_0=609601.22
+y_0=0
+ellps=GRS80
+units=m
+no_defs
+type=crs
```
because it directly uses the SRID in https://github.com/OSGeo/grass/blob/8b4ccfb47f34da4178bb24df5649fdf0f3ff4857/general/g.proj/output.c#L149

The ellipsoid parameters including `a` and `rf` from the first output come from
https://github.com/OSGeo/grass/blob/8b4ccfb47f34da4178bb24df5649fdf0f3ff4857/lib/proj/ellipse.c#L99-L101
and `towgs84` from
https://github.com/OSGeo/grass/blob/8b4ccfb47f34da4178bb24df5649fdf0f3ff4857/lib/proj/datum.c#L258

It's this towgs84 key causing the issue. Here is [a related Q&A](https://geopandas.org/en/stable/docs/user_guide/projections.html#i-get-a-bound-crs). In fact, I've tried different projections and `g.region -n` didn't work in any projection. I just got the same error.

**Comment by HuidaeCho** [comment]
@joneir Please try #2394.
