### ISSUE TITLE
[Feat] grass.jupyter naming

### ISSUE THREAD

**Issue by chaedri** [OSGeo/grass#2283]
**Please describe.**
With the release of version 8.2, it would be nice to have a relatively stable API for grass.jupyter, the python package making GRASS more accessible in Jupyter Notebooks. This feature request is just to solicit feedback on the current class/method names and gather possible alternatives if necessary.

**Describe the solution you'd like**
Here is an overview of the existing language:
* `GrassRenderer` and `Grass3dRenderer` create static renderings as png images that are embedded in the notebook
* `InteractiveMap` creates interactive maps using folium (leaflet library for Python)
* `TimeSeries` is a class for creating space time dataset visualizations. Users add layers to the visualizations with `TimeSeries.baselayer.d_*` and `TimeSeries.overlay.d_*` where the wildcard is any display module (for example `d_rast`).
* `TimeSeries.animate()` displays a GIF animation of the space time dataset
* `TimeSeries.time_slider()` displays an ipywidget datetime slider and rendering.

**Describe alternatives you've considered**
Please feel free to comment with alternative ideas or feedback on the existing names.

**Additional context**
You can test out grass.jupyter and the classes listed here in at the following binder links:
* [GrassRenderer and more](https://mybinder.org/v2/gh/OSGeo/grass/main?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Fgrass_jupyter.ipynb)
* [TimeSeries](https://mybinder.org/v2/gh/chaedri/grass/Jupyter-Timeseries?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Ftemporal.ipynb)
* [GRASS-folium Integration](https://mybinder.org/v2/gh/chaedri/grass/GRASS-folium?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Fgrass_jupyter.ipynb)

**Comment by neteler** [comment]
Thanks for having this discussion.

I have one (maybe not very obvious) point.

While this name is pretty clear and without hinting at the underlying technology:

> * `InteractiveMap` creates interactive maps using folium (leaflet library for Python)

these names are less so:

> * `GrassRenderer` and `Grass3dRenderer` create static renderings as png images that are embedded in the notebook

I wonder if `Grass` should be part of the name. Perhaps `MapRenderer` and `Map3dRenderer` or the like might be more obvious and omit the name of the underlying software (which is clear anyway), like `InteractiveMap` or `TimeSeries`?

Then I am unsure about `TimeSeries`.* if it "only" does visualizations while not having this in its name:
> * `TimeSeries`.* ... creating space time dataset **visualizations.**..

Not sure if I was able to express the differences sufficiently. Just my 0.02 cents :-)

**Comment by petrasovaa** [comment]
> * `TimeSeries.animate()` displays a GIF animation of the space time dataset
> * `TimeSeries.time_slider()` displays an ipywidget datetime slider and rendering.

Regarding time_slider(), I think Show() would be more consistent. There seems to be a [widgets.Play](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html?highlight=play#Play-(Animation)-widget) widget that could be used here for better control? Then we wouldn't need animate(). I think viewing the time series using this play widget is better than showing a GIF, GIFs are good for exporting animation but they are not interactive, the colors are worse so I am thinking something 
like TimeSeries.gif(filename=None) could be better and primary tool for animating would be the Play widget (if possible).

**Comment by petrasovaa** [comment]
> I wonder if `Grass` should be part of the name. Perhaps `MapRenderer` and `Map3dRenderer` or the like might be more obvious and omit the name of the underlying software (which is clear anyway), like `InteractiveMap` or `TimeSeries`?

Map
Map3d
InteractiveMap
TimeSeriesMap

Map is not exactly matching the terminology used in GRASS (raster map, vector map), but it may be clearer for others.

**Comment by wenzeslaus** [comment]
Notes from a meeting between @chaedri, @petrasovaa and @wenzeslaus:

## Base/main name for the display/render classes

| Name     | Evaluation |
| -------  | ---------- |
| Map      | Spatial is the main purpose, even when there are non-spatial things |
| Plot     | More associated with non-spatial data |
| Figure   | Often refers to a combination of multiple images and text which is not the primary association we want |
| Monitor  | Seems to refer to the physical thing or the process these days |
| Display  | Seems more interactive and not used much in this context, perhaps too general |
| Renderer | Not a common word, not in dictionary |
| Plotter  | Not used in this context |
| Image    | Too many images already (IPython, PIL/Pillow) |

_Map_ has an disadvantage that an instance of the class cannot be called map because that would shadow a Python build-in function _map_. However, that issue may be mitigated by using an adjective:

```
plot = TimeSeriesPlot()
fig = TimeSeriesFigure()
map = TimeSeriesMap()
temperature_map = TimeSeriesMap()
```

Notably, _m_ would not work either because that would trigger a Flake8 warning and may trigger  a spell check warning. The standard way in Python how to deal with shadowing a build-in or keyword is using a trailing underscore, i.e., _map__. That would not work well for examples, but there naming it with some adjective is likely the best option because in cases like notebooks, there will be more than one map.

Another disadvantage of _map_ is that map means the _data values mapped on space_ thing in GRASS. However, _map_ is used in the more cartographic meaning as in _Map Display_ in GUI and default file name for display commands is _map.png_, so using _map_ in the data display is not a foreign concept either.

## Full names for classes

| New Name | Alternative | Original Name | Description |
| -------  | ----------- | ------------- | ----------- |
| Map      |             | GrassRenderer | Interface to display modules |
| Map3D    | Map3d       | Grass3DRenderer | 
| InteractiveMap | | (not changed) | Simple interface to Folium |
| TimeSeriesMap | TemporalMap | TimeSeries | Rendering of spatio-temporal datasets |

_TimeSeriesMap_ will fit well with a planned class for handling animations or series of data not managed by the temporal framework which can be named _SeriesMap_, so there is _TimeSeriesMap_ and _SeriesMap_.

For TimeSeriesMap, the following options were considered: TemporalMap, TemporalSeriesMap, MapSeries, SeriesMap, TimeSeriesMap, StdsMap, STDSMap, SpatioTemporalDataSetMap, SpatioTemporalDatasetMap TimeSeriesPlot, TimeSeriesVisualization, TimeSeriesVis.

## Map (2D) API

The 2D map currently makes the filename accessible with a property called _filename_ which is convenient in some cases like further processing. You can also specify name in the constructor which is useful for some advanced scripting. However, to be consistent with TimeSeriesMap and InteractiveMap, a new _save_ method is needed:

```python
nc_map = Map()
nc_map.filename
nc_map.save("myfile.png")
```

The method will have to convert (or alternatively fail) when file is not the same format as the underlying file.

## TimeSeriesMap API

```python
hydro_map = TimeSeriesMap(...)
hydro_map.baselayer.d_rast(map="elevation")
hydro_map.add_time_series(name="hydrology", element_type="strds")
hydro_map.overlay.d_vect(map="roads")
hydro_map.d_legend()
hydro_map.add_timestamp(...)
hydro_map.show()
```

- No time series specified in the constructor/init call.
- Time series is two words (time_series not timeseries).
- Base layers are specified before the time series name.
- Functions which are not using display modules (tools, commands, functions) directly start with _add__ as in _InteractiveMap_.
- A new function for adding a timestamp replaces parameters of the original GIF animate with display command implementation and is applicable to the interactive widget as well.
- The two functions for interactive notebook display and file export are called _show_ and _save_.

The _save_ function works with a single GIF as a filename:

```python
hydro_map.save("myfile.gif")
```

Maybe you can specify format explicitly in the future:

```python
hydro_map.save("myfile.gif", format="gif")
hydro_map.save("mydirectory", format="png")
```

Generally, format is determined from extension. GIF means single file. PNG means multiple files:

```python
hydro_map.save("mydirectory/myfile.png")
# Now you have mydirectory/myfile_001.png mydirectory/myfile_002.png ...
```

To enable further use of the files when the file names are generated internally, the function returns the file names:

```python
assert hydro_map.save("mydirectory/myfile.png") == ["mydirectory/myfile_001.png", "mydirectory/myfile_002.png", ...]
```

Even in the case of a single file, the file name is returned as a string (or maybe Path) so that it can be used in examples in a notebook with IPython Image for display:

```python
Image(hydro_map.save("myfile.gif"))
```

A future SeriesMap for non-temporal data would have the same API except for the _add_time_series_ function which would be perhaps _add_series_ with a list of rasters or  _add_rasters(names, labels)_, _add_vectors_, _add_raster3d(name, slice="horizontally", labels)_, ...

**Comment by wenzeslaus** [comment]
Some additional thoughts by @petrasovaa and @wenzeslaus:

## Unifying TimeSeriesMap and SeriesMap API

TimeSeriesMap and (theoretical) SeriesMap can have the same function names for adding temporal data and series of data:

```python
temporal_map = TimeSeriesMap()
temporal_map.add_raster_series(name="...", ...)
temporal_map.add_vector_series(name="...", ...)

non_temporal = SeriesMap()
non_temporal.add_raster_series(names=[...], labels=[...], ...)
non_temporal.add_vector_series(names=[...], labels=[...], ...)
```

`...` represents _d.rast_ and _d.vect_ parameters (this is not addressed in the current API).

**Comment by veroandreo** [comment]
I´d like to give an opinion but need a lil time to read carefully and think a bit, hope to do so by this weekend

**Comment by veroandreo** [comment]
Despite the disadvantages, I like `Map`. I think this is how we all call cartographic/geographic figures. Now, since for the interactive class we use the adjective, why not using an adjective for the static maps too? Something like: 
- StaticMap
- Static3dMap
- InteractiveMap
- TimeSeriesMap (TimeSeriesPlot is more like what g.gui.tplot does in my view, so I'd discourage that name in this context of maps)

In this way the use of the word `Map` seems more consistent to me. My 0.02 cents :)

**Comment by chaedri** [comment]
Thank you all for your input. After a discussion today, @wenzeslaus, @petrasovaa and I opted for:

- GrassRenderer -> Map
- Grass3dRenderer -> Map3D
- InteractiveMap
- TimeSeries -> TimeSeriesMap

We felt that Map and Map3D did not need an adjective (like static) before because they are the base class used in TimeSeriesMap and Interactive map and because it keeps the class name shorter.
