### ISSUE TITLE
clang-format error: unknown enumerated scalar

### ISSUE THREAD

**Issue by marisn** [OSGeo/grass#2839]
```
.clang-format: Invalid argument
.clang-format:8:3: error: unknown enumerated scalar
  Enabled: true
```
```
clang-format --version
Debian clang-format version 14.0.6
```

**Comment by nilason** [comment]
The .clang-format file is version 15+ compatible (see [submitting_c.md](doc/development/submitting/submitting_c.md#source-code-formatting)).

I initially aimed for version 13 compatibility, but learning the easy way to install with pip (eg. `python -m pip install 'clang-format==15.0.6'`) I stayed with 15 in order to limit the possibility of potential differences from using various versions. 
If you install [pre-commit](doc/development/submitting/submitting.md#use-pre-commit) (something I dearly recommend!) all necessary tools (incl. clang-format) will be installed with the right version in a dedicated python environment.

Closing this as invalid.
