### ISSUE TITLE
Problem with i18n

### ISSUE THREAD

**Issue by slichtzzz** [OSGeo/grass#2867]
Part of the line is not translated. Similar to the issue discussed earlier here (https://github.com/OSGeo/grass/issues/2805).

Here the begenning of string "Draw sample region " is translated, but the lower part with " of " is given in English.

https://github.com/OSGeo/grass/blob/main/gui/wxpython/rlisetup/wizard.py#L1236

**Comment by wenzeslaus** [comment]
Correct, this needs one string in the translate function call (`_()`) and a format function call on the result (`_(...).format(...)`. Would you consider creating a PR?

**Comment by slichtzzz** [comment]
I am ready to help, but not very good at python )
Should it be something like: _("Draw sample region {0} of {1}".format(self.regioncount, numregions))?

**Comment by wenzeslaus** [comment]
This is a good first issue! :-)

1. The format call needs to be on whatever the `_` function returns, so `_("...").format(...)`. This way, the formatting (value substitution) will happen on the translated string, not the original English string.

2. Instead of using the numbers (or empty `{}`), the best practice is to use what Python calls keyword arguments for the format function `...format(number=..., total=...)`. Then you can [use these names to identify the values](https://docs.python.org/3/tutorial/inputoutput.html#the-string-format-method) in the string: `{number}`. The names are visible to the person translating the string and they can even change their order.

**Comment by slichtzzz** [comment]
Thank you so much! Your exlanations are so easy to grasp!
So, I think the below code would work fine:
 _("Draw sample region {rcount} of {numr}").format(rcount=self.regioncount, numr=numregions)

:-)

**Comment by veroandreo** [comment]
> Thank you so much! Your exlanations are so easy to grasp! So, I think the below code would work fine: _("Draw sample region {rcount} of {numr}").format(rcount=self.regioncount, numr=numregions)
> 
> :-)

Go ahead and create the pull request :nerd_face:

**Comment by wenzeslaus** [comment]
That looks good. Lately we are trying to use variable names which would pass spell check, so e.g., count and num_regions. The names are local to this line (to the format function call), so no need to make them unique. Do you want to continue this in a PR? ...as @veroandreo says :-)

**Comment by slichtzzz** [comment]
Ok then, count and num_regions :-)

_("Draw sample region {count} of {num_regions}").format(count=self.regioncount, num_regions=numregions)

So, now I will continue with a pull request.

**Comment by sumit-158** [comment]
@slichtzzz If you are not working Can I work on it?
cc: @veroandreo

**Comment by nilason** [comment]
This was fixed with #2869.
