### ISSUE TITLE
r.walk: rename lambda to scaling

### ISSUE THREAD

**Issue by baharmon** [OSGeo/grass#3026]
**Describe the bug**
The lambda parameter in r.walk is a reserved keyword in Python so this parameter cannot be used in Python scripts.

```
lambda=0.5
SyntaxError: invalid syntax
```

**To Reproduce**

```
import grass.script as gscript

# settings
env = gscript.gisenv()
overwrite = True
env['GRASS_OVERWRITE'] = overwrite
env['GRASS_VERBOSE'] = False
env['GRASS_MESSAGE_FORMAT'] = 'standard'
gisdbase = env['GISDBASE']
location = env['LOCATION_NAME']
mapset = env['MAPSET']

# set rules
rules = """\
1:3:0.1:0.1
4:5:10.:10.
6:6:1000.0:1000.0
7:7:0.3:0.3
"""

# set region
gscript.run_command(
    'g.region',
    n=220420,
    s=215020,
    e=637720,
    w=632320,
    res=28.5
)

# recode landcover
gscript.write_command(
    'r.recode',
    input='landclass96',
    output='friction',
    rules='-',
    stdin=rules,
    overwrite=overwrite
)

# compute walkshed
gscript.run_command(
    'r.walk',
    elevation='elevation',
    friction='friction',
    output='walkshed',
    start_coordinates=(635576,216485),
    lambda=0.5,
    max=10000,
    overwrite=overwrite
)
```

**Expected behavior**
You should be able to set this parameter in a Python script. I propose changing *lambda* to *scaling* since it is a dimensionless scaling factor of the friction cost.

**System description:**

- Operating System: Windows 10
- GRASS GIS version 8.2.1
- version=8.2.1
- date=2023
- revision=9468133b8
- build_date=2023-01-23
- build_platform=x86_64-w64-mingw32
- build_off_t_size=8
- libgis_revision=9468133b8
- libgis_date=2023-01-21T17:40:37+00:00
- proj=9.1.1
- gdal=3.6.2
- geos=3.11.1
- sqlite=3.39.4

**Comment by neteler** [comment]
Suggestion: Prepend an underscore to the name, i.e.: ` _lambda`

**Comment by pesekon2** [comment]
> Suggestion: Prepend an underscore to the name, i.e.: ` _lambda`

Leading underscores should be used as hints for internal use. The correct one here would be a trailing underscore, ide est `lambda_`

**Comment by wenzeslaus** [comment]
Adding the trailing underscore is a common practice in Python, but I think the amount of experience you need to guess that it will work here is quite high. We may add more documentation to clarify that. Perhaps something to discuss together with documentation renewal.

As for the "lambda to scale or scaling" rename, there are other reasons to do this. We may decide to avoid Python and SQL keywords in general. We may decide to prefer more descriptive names rather than Greek letters as names...

These are discussions for a separate issue, I'm closing this one as not planned at the moment. Feel free to follow up with a general on this topic.
