### ISSUE TITLE
[Feat] make gscript.create_location() callable from outside

### ISSUE THREAD

**Issue by pesekon2** [OSGeo/grass#3034]
**Is your feature request related to a problem? Please describe.**

It is impossible to create a new GRASS GIS location without an already existing one. In the current state, you need GRASS GIS to be initialized prior to calling `gs.create_location()`. However, you cannot call `gs.setup.init()` without having a location. 

**Describe the solution you'd like**

`gs.create_location()` does not need `gs.setup.init()` to be called beforehand. 

* Check for GISBASE: no GISBASE -> `setup_runtime_env()`
* Check for GISRC: no GISRC -> `_create_location_xy(dbase, location)`
* Follow as usual

**Describe alternatives you've considered**

`gs.setup.init()` creating a location.

**Workaround so far**

Create location by calling a subprocess. Dirty, ugly, and nasty, but it works.

**Comment by wenzeslaus** [comment]
I made minor edits to the names and flipped the order of GISBASE and GISRC checks. Although they are independent, checking for runtime and then for data makes more sense because that's how they are set up, first runtime, then data.

**Comment by wenzeslaus** [comment]
@pesekon2 We talked about this in Prague and if I recall correctly, the description in the issue is the result of the discussion. Have you ever created any code to implement this? Or do you have some code you are already using to workaround it? I vaguely recall there was an issue or PR perhaps in another repo somewhere.

I can work on this and I'm gathering information.

**Comment by pesekon2** [comment]
I had some workaround somewhere but the works were always postponed. Thanks for looking at that instead.
