### ISSUE TITLE
[Bug] CI: travis does not find ubuntu ppa

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#3202]
By chance I discovered that this line fails:

https://github.com/OSGeo/grass/blob/632b22970ea287d33a313b08052eab26867a033d/.travis/linux.before_install.sh#L7

```
...
Setting up build cache

$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ./.travis/$TRAVIS_OS_NAME.before_install.sh
Cannot add PPA: 'ppa:~ubuntugis/ubuntu/ubuntugis-unstable'.
The team named '~ubuntugis' has no PPA named 'ubuntu/ubuntugis-unstable'
Please choose from the following available PPAs:
 * 'ppa':  ubuntugis-stable
 * 'ubuntugis-experimental':  ubuntugis-experimental
 * 'ubuntugis-testing':  ubuntugis-testing
 * 'ubuntugis-unstable':  ubuntugis-unstable

The command "./.travis/$TRAVIS_OS_NAME.before_install.sh" failed and exited with 1 during .
Your build has been stopped.
```

See log: https://app.travis-ci.com/github/OSGeo/grass/jobs/611517273

**Comment by neteler** [comment]
>  I updated from Ubuntu 20.04 to 22.04 which solved the problem

Do be honest, I don't understand what has to be changed.

**Comment by wenzeslaus** [comment]
It seems that the PPA issue is fixed. I don't think it was anything in this repo. The main in this repo built successfully 5 days ago and PRs are building.

However, the main does not build anymore due to permissions. Its says: "Sender {name} is not allowed to trigger build in this repo." I don't see any settings in the [repo page](https://app.travis-ci.com/github/OSGeo/grass). I guess I don't have permissions (I have Settings under More options for my repos).

It's a separate issue from the OP, but who has the permissions for Travis?

> > I updated from Ubuntu 20.04 to 22.04 which solved the problem
> 
> To be honest, I don't understand what has to be changed.

For me, updating from Ubuntu 20.04 to 22.04 fixed the PPA issue.

**Comment by wenzeslaus** [comment]
Travis check is running again (Travis CI - Branch Successful in 9m - Build Passed). Thanks for fixing the permission issue. I'm closing this as completed since the PPA issue is no longer present either.
