### ISSUE TITLE
[Bug] CI: Bandit: 1 configuration not found (python-code-quality.yml)

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#3682]
## Describe the bug

This just came to my attention while checking open PRs:

Actions workflow (python-code-quality.yml) complains about:

```
1 configuration not found

Warning: Code scanning cannot determine the alerts introduced by this pull request, because 1 configuration present on refs/heads/main was not found:
Actions workflow (python-code-quality.yml)

    ❓  .github/workflows/python-code-quality.yml:python-checks/bandit-version:1.7.8/black-version:23.1.0/flake8-version:3.9.2/min-python-version:3.7/os:ubuntu-22.04/pylint-version:2.12.2/python-version:3.10
```

See e.g.:

https://github.com/OSGeo/grass/pull/3671

![image](https://github.com/OSGeo/grass/assets/1295172/2252b38c-2dea-4e45-9343-b7fc3664a6ec)

--> https://github.com/OSGeo/grass/runs/24278615418

If this is known/expected just close this report.

**Comment by echoix** [comment]
I see where it comes from. A similar thing happened for CodeQL when we adjusted the languages names. Since the strategy matrix values are used to generate the configuration slug, changing any strategy matrix will create a different configuration.

Here, it's because it still expects results from the configuration that had the old black version like before.

The way out: 
1) in GitHub security scanning tab, delete the old configuration. This will solve for this time.
Or
2) Change the strategy matrix values with tool versions to job-level or workflow-level env vars instead. We will probably need to adjust the required status checks to the new name of the check if it used that job, and that would be a good thing.

**Comment by wenzeslaus** [comment]
I don't see anything in the security tab for the name of the configuration or a button to delete it. I see links to the workflow. Rest is read-only. Screenshots attached. Let me know if there is anything I can explore more.

![Screenshot from 2024-05-05 20-35-59](https://github.com/OSGeo/grass/assets/5449060/e3424c01-ecaa-4744-a0b8-8c70af23dc97)
![Screenshot from 2024-05-05 20-35-31](https://github.com/OSGeo/grass/assets/5449060/310867d7-9533-45c7-8101-bdfa4b36b53c)

**Comment by echoix** [comment]
I went and delete it a while after, the same or next day after no answer.

**Comment by echoix** [comment]
Since #3799, this shouldn't happen with this workflow, until the matrix strategy is changed, like when the runner OS will change to Ubuntu 24.04. Otherwise I can always go and "delete" the old configuration (just the key/label) when only the new one is uploading results.
