### ISSUE TITLE
[Bug] Need to reinstall all addons after each update - libgis version incompatibility

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass#632]
Because of libgis version being the hash code, after every time I recompile grass dev, I get these:

```
Details: <ERROR: Module built against version f062bffc8 but trying to use version
       f89b009b5. You need to rebuild GRASS GIS or untangle multiple
       installations.
```
for every addon I have installed. Hence, after every update, I have to recompile all installed addons. Is it possible to avoid this somehow?

**Comment by metzm** [comment]
The git hash in the error message refers to the latest change to `include/`, i.e. if any GRASS C header changed, you need to recompile or reinstall addons, otherwise they are not binary compatible and would crash with unpredictable errors. For example, the latest git hash change for grass master is f89b009b from 2020-04-24. The latest git hash change to grass-7.8.dev is 8e4dab57 from 2020-05-05.

This is not a bug, but a re-enabled (originally designed for svn) feature to ensure binary compatibility of C addons.

A corresponding test for Python addons (latest change in lib/python) is yet missing.

**Comment by wenzeslaus** [comment]
@veroandreo Simple `g.extension.all` should update the modules.

**Comment by veroandreo** [comment]
yes, that's what I did. 
Thanks for the explanation, @metzm :)
I close this issue with invalid label
