### ISSUE TITLE
[Feat] startup GUI automatic detection of grassdata: make case independent

### ISSUE THREAD

**Issue by mlennert** [OSGeo/grass#644]
In the current implementation, the startup gui screen automatically detects a grassdata directory if present, but it does not detect GRASSDATA, Grassdata, GrassData, or any other possible combinations of case.
IMHO this detection should be case independent to allow for different cultures of case usage in file and directory naming.
[I could even imagine going a step further and detecting all directories with the word grassdata in them and providing the list for the user to chose from. This would allow the user to separate their data into several GRASS databases if so desired and make it easy to launch in whatever they want to use. But that idea is maybe better discussed in another issue if anyone finds it necessary.]

**Comment by wenzeslaus** [comment]
@mlennert Can you please test master and close?

**Comment by mlennert** [comment]
In its current form, the code gives preference to grassdata over GRASSDATA, and preference to GRASSDATA over Grassdata. This means that if you have an empty grassdata and a GRASSDATA filled with locations, it will still privilege the former. This is due to simple alphabetic ordering of the os.walk(candidate), but is a bit annoying. Maybe a check should be added to go through all existing candidates and see if they contain anything and rather chose as default an existing directory that actually has locations in it ?

Ideally, the startup should detect all possible candidates and propose a choice to the user. But maybe this is overkill.

I personally also prefer uppercase directory names and so wouldn't have chosen 'grassdata' as the default name of the directory to create if none exist, but this is not important enough for me to argue about it ;-)

**Comment by wenzeslaus** [comment]
> This means that if you have an empty grassdata and a GRASSDATA filled with locations, it will still privilege the former...rather chose as default an existing directory that actually has locations in it ?

What is the use case you are trying to address? It seems very narrow. Users with bunch of empty randomly named "grassdata" directories?

> Ideally, the startup should detect all possible candidates and propose a choice to the user...

Users who are actually using multiple directories will be addressed by #741. Don't forget this issue is addressing _first time start of GRASS GIS in case there is an existing "grassdata" directory_ (later it uses the last one used).

> I personally also prefer uppercase directory names and so wouldn't have chosen 'grassdata' as the default name of the directory to create if none exist...

I think the name of the directory is open to discussion, but `grassdata` is what we currently have everywhere in documentation as far as I recall. I don't think the convention you are using is that common to make it the preferred one. It would be more likely that we would change it to something like `GrassData` or `GrassSpatialDatabase` in order to follow what operating systems are using (`Document`, `Music`, ...) and to behave like other software (`PlayOnLinux's virtual drives`, `R`, `Dropbox`). A topic for a new issue if needed.

Besides this, does this work for you as advertised? Can we close this?

**Comment by mlennert** [comment]
Yes. It works.
