### ISSUE TITLE
[Bug] v.to.db columns=name[,name,...] [required] - ERROR: Column <xcoor> exists. To overwrite, use the --overwrite flag

### ISSUE THREAD

**Issue by hellik** [OSGeo/grass#770]
**Describe the bug**

according to the v.to.db manual:

```
columns=name[,name,...] [required]
    Name of attribute column(s) to populate
    Name of attribute column(s)
```

you can select already existing columns where the parameter(s) should be uploaded. 

in earlier GRASS version it worked  in that way. e.g. used in one of my [addons](https://github.com/OSGeo/grass-addons/blob/master/grass7/vector/v.fixed.segmentpoints/v.fixed.segmentpoints.py#L165)

```
    grass.run_command("v.to.db", map = voutpoint,
                                     option = 'coor',
                                     layer = 1, 
                                     columns = 'xcoor,ycoor')
```

now it seems that v.to.db with already existing columns you get:

```
ERROR: Column <xcoor> exists. To overwrite, use the --overwrite flag
```

was there a change in the behaviour?

**System description (please complete the following information):**

```
System Info                                                                     
GRASS Version: 7.8.3                                                            
Code revision: 8bcecc9a6                                                        
Build date: 2020-05-05                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.0.4                                                                     
PROJ: 6.3.2                                                                     
GEOS: 3.8.1                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.19041-SP0 (OSGeo4W) 
```

**Additional context**

**Comment by HuidaeCho** [comment]
Related commit #487 and discussion https://trac.osgeo.org/grass/ticket/3466. Personally, I don't like that this module just creates new columns. With no existing columns, it *just* works. Without the --overwrite flag, again, it used to *just* work even if specified columns already exist. There was no way to tell if columns existed before and were overwritten or they were created by this module. I believe that this behavior makes the user either more confused or less careful. The --overwrite flag was implemented to avoid *accidental* overwriting of existing columns.

1. Columns have to be created manually (early behavior). Leave column creation up to the user.
2. Columns can be created automatically or overwritten without any warnings (your expected behavior before this PR)
3. Columns can be created automatically, but overwriting existing columns requires the --overwrite flag (current behavior)

Personally, I prefer option 1, but if we have to create columns automatically, I prefer option 3 over 2.

**Comment by hellik** [comment]
ok, I missed the discussion. closing the issue.

it seems it was never checked if addons are using the old behaviour. I'll adapt my addons accordingly.

>Personally, I prefer option 1, but if we have to create columns automatically, I prefer option 3 over 2.

I agree with this option order.
