### ISSUE TITLE
[Bug] tools/mkhtml.py doesn't correctly generate the URL to commits in case of addons

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#979]
Each manual page provides two links at page bottom:

```
SOURCE CODE

Available at: <module> source code (history)
```
e.g.
https://grass.osgeo.org/grass78/manuals/v.to.rast.html#authors

![image](https://user-images.githubusercontent.com/1295172/93689682-24c1a200-fad1-11ea-99b3-e784297382a5.png)

The code generating these links is here:

https://github.com/OSGeo/grass/blob/fd835a5f097af00427303ef54d8fbea987415e67/tools/mkhtml.py#L386

**Problem**

While this works fine for code modules, it fails for addons:

E.g.,
https://grass.osgeo.org/grass7/manuals/addons/r.in.pdal.html#authors

The reason is that

`URL_LOG=url_source.replace('grass/tree',  'grass/commits')))`

should be in case of an addon

`URL_LOG=url_source.replace('grass-addons/tree',  'grass-addons/commits')))`

The question is: how to detect in `tools/mkhtml.py`  when an *addon* manual page is generated?

**Comment by tmszi** [comment]
> The question is: how to detect in `tools/mkhtml.py` when an _addon_ manual page is generated?

During instalation addon via g.extension I try download all addons paths json file ('addons_paths.json' file is created in the $GRASS_ADDON_BASE dir) via github api. Check function [get_addons_paths()](https://github.com/OSGeo/grass/pull/987/commits/433b8ef0bf4e7235d6cd1f209c9515e00f005815/#diff-58ae09416c2574f4eb2c0dbd6b0470d1R2178). 

```
curl https://api.github.com/repos/OSGeo/grass-addons/git/trees/master?recursive=1
```

After that in mkhtml.py file I try open/parse this json file and [detect if module is addon](https://github.com/OSGeo/grass/pull/987/commits/433b8ef0bf4e7235d6cd1f209c9515e00f005815#diff-1b8d8150c23ad179c31ae284d84a3ed4R411) and get corrected addon path (especially for GUI addons, because default build GUI addons module base url path is incorrect. Simple example wx.metadata, v.info.iso module, default builded url path is https://github.com/OSGeo/grass-addons/tree/master/grass7/vector/v.info.iso, but correct url path is https://github.com/OSGeo/grass-addons/tree/master/grass7/gui/wxpython/wx.metadata/v.info.iso).

Could @neteler test it, please?

**Comment by neteler** [comment]
After merge & backport it now runs on the server:

Random addon: https://grass.osgeo.org/grass7/manuals/addons/i.fusion.hpf.html
- Available at: i.fusion.hpf source code --> points to the right source code directory, nice.
-  (history) --> points to the same while expected (and seen in the source code of #987) it should be pointing to "commits"

**Comment by tmszi** [comment]
> After merge & backport it now runs on the server:
> 
> Random addon: https://grass.osgeo.org/grass7/manuals/addons/i.fusion.hpf.html
> 
>     * Available at: i.fusion.hpf source code --> points to the right source code directory, nice.
> 
>     * (history) --> points to the same while expected (and seen in the source code of #987) it should be pointing to "commits"

If I try install this add-on (localhost) I got error message:

```
Traceback (most recent call last):
  File "/tmp/grass7-tomas-17261/tmpk9piwhij/i.fusion.hpf/scripts/i.fusion.hpf", line 201, in <module>
    from high_pass_filter import get_high_pass_filter, get_modulator_factor, get_modulator_factor2
ModuleNotFoundError: No module named 'high_pass_filter'
```

**Comment by neteler** [comment]
I'll check but it applies to all commands listed here:  https://grass.osgeo.org/grass7/manuals/addons/ (e.g. https://grass.osgeo.org/grass7/manuals/addons/v.stats.html). I refer to how it is rendered on the server.

**Comment by tmszi** [comment]
> I'll check but it applies to all commands listed here: https://grass.osgeo.org/grass7/manuals/addons/ (e.g. https://grass.osgeo.org/grass7/manuals/addons/v.stats.html). I refer to how it is rendered on the server.

Yes, you are right. I'll look into it again.

**Comment by tmszi** [comment]
Could @neteler tell me more about how the add-on man page update process works on the server, please?

**Comment by neteler** [comment]
Sure, this is the script/cronjob:

https://github.com/OSGeo/grass-addons/blob/master/tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh

with the other scripts being in the same directory.

**Comment by tmszi** [comment]
> Sure, this is the script/cronjob:
> 
> https://github.com/OSGeo/grass-addons/blob/master/tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
> 
> with the other scripts being in the same directory.

Thanks Markus, Could @neteler  try this [PR,](https://github.com/OSGeo/grass-addons/pull/307) please?

**Comment by neteler** [comment]
Thanks for your efforts, I'd suggest to merge

**Comment by neteler** [comment]
Works fine now, closing as solved.
